# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='zone_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
