# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0002_school_zone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sniffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('number', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sats.School')),
            ],
        ),
        migrations.CreateModel(
            name='SnifferRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=64)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sniffer_no', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='max_address',
            new_name='mac_address',
        ),
    ]
