# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0003_auto_20170413_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnifferRead',
            new_name='SnifferUpdate',
        ),
    ]
