# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0004_auto_20170413_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnifferUpdate',
            new_name='TagUpdate',
        ),
    ]
