# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0005_auto_20170413_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagupdate',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='tagupdate',
            name='sniffer_no',
        ),
        migrations.AddField(
            model_name='tagupdate',
            name='sniffer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sats.Sniffer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagupdate',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sats.Tag'),
            preserve_default=False,
        ),
    ]
