# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0006_auto_20170413_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sats.School'),
        ),
        migrations.AddField(
            model_name='school',
            name='start_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
