# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0008_auto_20170413_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childguardian',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sats.Child'),
        ),
        migrations.AlterField(
            model_name='childguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sats.Guardian'),
        ),
    ]
