# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0009_auto_20170413_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sniffer',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='mac_address',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
